redis_url = ""
password = ""
context_length = 0
log_level = ""
system_prompt = """"""
concurrent = 0
enable_msg = ""
start_msg = ""
reset_msg = ""
queuing_msg = ""

[bot]
token = ""
proxy = ""

[text]
api_key = ""
api_base = ""
model = ""
provider = ""
temperature = 0.0
max_tokens = 0
top_p = 0.0
proxy = ""